"""Generate slides/dates.tex from web/weeks.toml.

The timetable lives in one place: web/weeks.toml.  This turns it into LaTeX
macros so the decks and handouts never hard-code a date.  For a week whose key
is `writing`, it defines:

    \\dateWriting        13 October
    \\dateWritingShort   13 Oct
    \\titleWriting       Academic Writing vs Encyclopedic Writing ...

Run it from the repository root (freeze.sh does this before building slides).
"""

import datetime
import pathlib
import tomllib

ROOT = pathlib.Path(__file__).parent
TOML = ROOT / "web" / "weeks.toml"
OUT = ROOT / "slides" / "dates.tex"


def camel(key: str) -> str:
    """week key -> macro-safe CamelCase (peer_review -> PeerReview)."""
    return "".join(part.capitalize() for part in key.split("_"))


def tex_escape(text: str) -> str:
    """Escape the characters that matter in the titles we emit."""
    for old, new in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                     ("$", r"\$"), ("#", r"\#"), ("_", r"\_")):
        text = text.replace(old, new)
    return text


def main() -> None:
    data = tomllib.loads(TOML.read_text(encoding="utf-8"))
    year = data.get("year", datetime.date.today().year)
    weeks = data["weeks"]

    lines = [
        "% Generated by make_dates.py from web/weeks.toml -- do not edit.",
        "% Change the timetable there, then run ./freeze.sh.",
        f"% Academic year: {year}",
        "",
    ]
    for key, week in weeks.items():
        month, day = (int(n) for n in week["date"].split("-"))
        when = datetime.date(year, month, day)
        name = camel(key)
        lines += [
            f"\\newcommand{{\\date{name}}}{{{when.day} {when:%B}}}",
            f"\\newcommand{{\\date{name}Short}}{{{when.day} {when:%b}}}",
            f"\\newcommand{{\\title{name}}}{{{tex_escape(week['title'])}}}",
        ]
    for brk in data.get("breaks", []):
        month, day = (int(n) for n in brk["date"].split("-"))
        when = datetime.date(year, month, day)
        name = camel(brk["key"])
        lines += [
            f"\\newcommand{{\\break{name}}}{{{when.day} {when:%B}}}",
            f"\\newcommand{{\\break{name}Short}}{{{when.day} {when:%b}}}",
            f"\\newcommand{{\\breakTitle{name}}}{{{tex_escape(brk['title'])}}}",
        ]
    for key, value in data.get("deadlines", {}).items():
        parts = [int(n) for n in value.split("-")]
        when = datetime.date(*parts) if len(parts) == 3 else datetime.date(year, *parts)
        name = camel(key)
        lines += [
            f"\\newcommand{{\\deadline{name}}}{{{when.day} {when:%B}}}",
            f"\\newcommand{{\\deadline{name}Short}}{{{when.day} {when:%b}}}",
        ]
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(weeks)} sessions, {year})")


if __name__ == "__main__":
    main()
